# Server settings (ServerProperties)
spring:
  application:
    name: eureka-server
server:
  address: localhost
  port: 8761
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/

security:
  basic:
    enabled: false
